services:
  - type: web
    name: oil-spill-detection-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: HUGGINGFACE_REPO
        value: sahilvishwa2108/oil-spill-detection-models
      - key: CORS_ORIGINS
        value: https://oil-spill-detection.vercel.app,https://oil-spill-frontend-oigeradm3-sahil-vishwakarmas-projects.vercel.app
      - key: PYTHONUNBUFFERED
        value: "1"
