[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
CORS_ORIGINS = "https://oil-spill-detection-frontend.vercel.app,http://localhost:3000"
LOG_LEVEL = "INFO"
