[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
CORS_ORIGINS = "https://oil-spill-frontend-gnc9e75af-sahil-vishwakarmas-projects.vercel.app,http://localhost:3000"
LOG_LEVEL = "INFO"
HUGGINGFACE_REPO = "sahilvishwa2108/oil-spill-detection-models"
